if __name__ == '__main__':
    list = [67,5,89,12,101,51,10,23,45]
    list.insert(3,34)
    print(list)
    print(list)
    list.remove(51)
    print(list)
    list.append(93)
    print(list)
    list.sort()
    print(list)
    list.pop()
    print(list)
    list.reverse()
    print(list)
